<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 

<!DOCTYPE result [
  <!-- order matters -->
  <!ELEMENT result (firstName, lastName, studentId, anotherProperty, subjects)>
  <!ELEMENT firstName (#PCDATA)>
  <!ELEMENT lastName (#PCDATA)>
  <!ELEMENT studentId (#PCDATA)>
  <!ELEMENT anotherProperty (#PCDATA)>

  <!ELEMENT subjects (subject*)>
  <!ELEMENT subject (code, cp, mark, grade) >

  <!ELEMENT code (#PCDATA)>
  <!ELEMENT cp (#PCDATA)>
  <!ELEMENT mark (#PCDATA)>
  <!ELEMENT grade (#PCDATA)>
]>


<result>
  
  <!-- define firstName lastName and student id -->
  <firstName>John</firstName>
  <lastName>Smith</lastName>
  <studentId>1231234</studentId>
  <anotherProperty>ABC</anotherProperty>

  <!-- list of subjects -->
  <subjects>
    <subject>
      <code>MATH101</code>
      <cp>4</cp>
      <mark>85</mark>
      <grade>A</grade>
    </subject>

    <subject>
      <code>ECON111</code>
      <cp>5</cp>
      <mark>70</mark>
      <grade>B</grade>
    </subject>

    <subject>
      <code>CS100</code>
      <cp>5</cp>
      <mark>80</mark>
      <grade>A</grade>
    </subject>

    <subject>
      <code>LAW121</code>
      <cp>6</cp>
      <mark>75</mark>
      <grade>B</grade>
    </subject>
  </subjects>
</result>
